#!/usr/bin/env bash
#Creates the file 

# Find the PID of the '7-highlander.sh' process
highlander_pid=$(pgrep -f "7-highlander.sh")

if [[ -n $highlander_pid ]]; then
    echo "Killing the '7-highlander.sh' process with PID: $highlander_pid"
    # Send SIGTERM signal to stop the '7-highlander.sh' process
    kill -15 "$highlander_pid"
    # Create the signal file to notify the other script
    touch /tmp/stop_signal
else
    echo "Process '7-highlander.sh' is not running."
fi

