#!/usr/bin/env bash

#!/bin/bash

# Find the PID of the '7-highlander' process
highlander_pid=$(pgrep -f "7-highlander")

if [[ -n $highlander_pid ]]; then
    echo "Killing the '7-highlander' process with PID: $highlander_pid"
    # Send SIGTERM signal to stop the '7-highlander' process
    kill -15 "$highlander_pid"
else
    echo "Process '7-highlander' is not running."
fi

